#information
title: 프엠
url: "https://peu0em.com"

#setting
future: true
trailing_slash: false

#plugins:

kramdwon:
    auto_ids: false


#default
defaults:
    -
        scope:
            path: ""
        values:
            lang:
                current: "ko"
    -
        scope:
            type: "posts"
        values:
            layout: "post"
            permalink: "/p/:year/:month/:day/:title"
    -
        scope:
            path: "/i"
        values:
            permalink: ":path/:title"
    -
        scope:
            path: "/f"
        values:
            permalink: ":path/:title"